import turtle

screen = turtle.Screen()
screen.setup(width=500, height=500)
t = turtle.Turtle()
t.speed(3)
t.penup()
t.goto(0, -150)
t.pendown()
t.color("green")
t.pensize(10)
t.goto(0, 0)
t.penup()
t.goto(0, -90)
t.pendown()
t.fillcolor("green")
t.begin_fill()
t.goto(-40, -120)
t.goto(0, -130)
t.goto(0, -90)
t.end_fill()
t.penup()
t.goto(0, -30)  
t.setheading(0)  
t.pendown()
t.color("navy")      
t.fillcolor("navy")  
t.begin_fill()
t.circle(50)
t.end_fill()
t.penup()
t.goto(0, -20)  
t.setheading(0)
t.pendown()
t.color("light blue")
t.fillcolor("light blue")
t.begin_fill()
t.circle(40)
t.end_fill()
t.penup()
t.goto(0, -5)  
t.setheading(0)
t.pendown()
t.color("yellow")
t.fillcolor("yellow")
t.begin_fill()
t.circle(20)
t.end_fill()
t.hideturtle()
turtle.done()

